#!/bin/sh
set -eu

export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_DATA_DIRS="/run/host/usr/local/share:/run/host/usr/share:/var/lib/flatpak/exports/share:${HOME}/.local/share/flatpak/exports/share:${HOME}/.local/share:/var/lib/snapd/desktop:/app/share:/usr/share:/usr/local/share"

exec /app/bin/cosmic-status-hub-bin "$@"
